apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admission-controller
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admission-controller
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admission-controller
subjects:
  - kind: ServiceAccount
    name: admission-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: admission-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admission-controller
subjects:
  - kind: ServiceAccount
    name: admission-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-controller-webhook-service
  labels:
    run: admission-controller-webhook-service
spec:
  template:
    metadata:
      labels:
        run: admission-controller-webhook-service
    spec:
      serviceAccountName: admission-controller
      containers:
        - image: controller:v1.4
          name: admission-controller-webhook-service
          env:
            - name: POD_NAMESPACE
              value: default
          volumeMounts:
            - mountPath: /certs
              name: cert
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: admission-controller
  selector:
    matchLabels:
      run: admission-controller-webhook-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: admission-controller-webhook-service
  name: admission-controller-webhook-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    run: admission-controller-webhook-service
---
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: admission-controller-validating-webhook-configuration
webhooks:
  - name: admission-controller-webhook-service.default.svc
    clientConfig:
      service:
        name: admission-controller-webhook-service
        namespace: default
        path: /validate
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "configmaps"
        operations:
          - "CREATE"
    sideEffects: None
    admissionReviewVersions:
      - "v1"
---
kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: admission-controller-mutation-webhook-configuration
webhooks:
  - name: admission-controller-webhook-service.default.svc
    clientConfig:
      service:
        name: admission-controller-webhook-service
        namespace: default
        path: /mutate
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "configmaps"
        operations:
          - "CREATE"
          - "UPDATE"
    sideEffects: None
    admissionReviewVersions:
      - "v1"